server:
  port: 8080

spring:
  application:
    name: spring-redis

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring-redis
    username: user
    password: 123456
  flyway:
    enable: true

  data.redis:
    host: localhost
    port: 6379
    password: 123456

