server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.reactive: DEBUG

spring:
  application:
    name: spring-redis

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring-redis
    username: "user"
    password: "123456"
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/spring-redis
    user: "user"
    password: "123456"
    baseline-on-migrate: true
    locations: classpath:db/migration

  data.redis:
    host: localhost
    port: 6379
    password: 123456

app:
  security:
    token-configs:
      - type: ACCESS_TOKEN
        duration: P30d
      - type: REFRESH_TOKEN
        duration: P90d
    skip-api:
      - /public/**
      - /ui/login
      - /api/login
    public-key: "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+aELE6InoIIRtqEuiDaFKfNpFYwwk0R+S1tmAt4wi0PNwHo2+kOsvh2xWVdZm0xqpQ6/8Qbeu1kV1qwhRzxdtw=="
    private-key: "MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCBy63470Fb64RVuHZy1arFwmN+ARFkWW/A17NQWToHlKw=="


